# Generated by Django 2.1.4 on 2018-12-05 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queue', 'queue'), ('test', 'test'), ('pending', 'pending'), ('running', 'running'), ('completed', 'completed')], max_length=50)),
                ('file', models.ImageField(blank=True, default='output/no-img.jpg', null=True, upload_to='output/')),
                ('checkpoint', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=800)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('type', models.CharField(choices=[('photo', 'photo'), ('drawing', 'drawing'), ('print', 'print'), ('landscape', 'landscape')], max_length=100)),
                ('file', models.ImageField(default='sources/no-img.jpg', upload_to='sources/')),
            ],
        ),
        migrations.CreateModel(
            name='ResizedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(default='sources/no-img.jpg', upload_to='resized/')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resizes', to='art.Image')),
            ],
        ),
        migrations.AddField(
            model_name='artproject',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riffed', to='art.ResizedImage'),
        ),
        migrations.AddField(
            model_name='artproject',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred', to='art.ResizedImage'),
        ),
    ]
