# Generated by Django 2.1.4 on 2018-12-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_auto_20181205_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artproject',
            name='file',
        ),
        migrations.AddField(
            model_name='artproject',
            name='output_file',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artproject',
            name='checkpoint',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='artproject',
            name='source',
            field=models.CharField(default='b', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artproject',
            name='style',
            field=models.CharField(default='c', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('photo', 'photo'), ('drawing', 'drawing'), ('print', 'print'), ('landscape', 'landscape')], default='photo', max_length=100),
        ),
    ]
