# Generated by Django 2.1.4 on 2018-12-05 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_auto_20181205_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='artproject',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
